### ISSUE TITLE
Handle unknown cli keys

### ISSUE THREAD

**Issue by veirus** [genotrance/vire#1]
Win 8.1 x64, python 3.6 x64
Issue [not critical]: Vire throws error on unrecognized cli keys:
```
D:\env\temp\vire 
λ vire -z
usage: vire [-h] [-b] [-f] [-i] [-n] [-v] [vimrc]
vire: error: unrecognized arguments: -z
Traceback (most recent call last):
  File "d:\env\temp\vire\lib\site-packages\vire.py", line 365, in main
    setup()
  File "d:\env\temp\vire\lib\site-packages\vire.py", line 145, in setup
    parsecli()
  File "d:\env\temp\vire\lib\site-packages\vire.py", line 91, in parsecli
    args = parser.parse_args()
  File "C:\Users\Neil\AppData\Local\Programs\Python\Python36\lib\argparse.py", line 1733, in parse_args
    self.error(msg % ' '.join(argv))
  File "C:\Users\Neil\AppData\Local\Programs\Python\Python36\lib\argparse.py", line 2389, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "C:\Users\Neil\AppData\Local\Programs\Python\Python36\lib\argparse.py", line 2376, in exit
    _sys.exit(status)
SystemExit: 2
```
Also, for some reason there's error on `-h`
```
D:\env\temp\vire 
λ vire -h
usage: vire [-h] [-b] [-f] [-i] [-n] [-v] [vimrc]

positional arguments:
  vimrc          Gist ID or path to vimrc file

optional arguments:
  -h, --help     show this help message and exit
  -b, --bit32    Force 32-bit install
  -f, --force    Force Vim reinstall
  -i, --install  Install Vim/Neovim
  -n, --neomode  Neovim mode
  -v, --vimmode  Vim mode [default]
Traceback (most recent call last):
  File "d:\env\temp\vire\lib\site-packages\vire.py", line 365, in main
    setup()
  File "d:\env\temp\vire\lib\site-packages\vire.py", line 145, in setup
    parsecli()
  File "d:\env\temp\vire\lib\site-packages\vire.py", line 91, in parsecli
    args = parser.parse_args()
  File "C:\Users\Neil\AppData\Local\Programs\Python\Python36\lib\argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\Neil\AppData\Local\Programs\Python\Python36\lib\argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\Neil\AppData\Local\Programs\Python\Python36\lib\argparse.py", line 1968, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Users\Neil\AppData\Local\Programs\Python\Python36\lib\argparse.py", line 1908, in consume_optional
    take_action(action, args, option_string)
  File "C:\Users\Neil\AppData\Local\Programs\Python\Python36\lib\argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Users\Neil\AppData\Local\Programs\Python\Python36\lib\argparse.py", line 1021, in __call__
    parser.exit()
  File "C:\Users\Neil\AppData\Local\Programs\Python\Python36\lib\argparse.py", line 2376, in exit
    _sys.exit(status)
SystemExit: 0
```

**Comment by genotrance** [comment]
This was an issue with the global try/except which was incomplete. I've fixed it in v0.1.2. Thanks.
